CREATE TABLE IF NOT EXISTS Regions (
  Id BIGSERIAL PRIMARY KEY,
  Name text NOT NULL UNIQUE,
  CHECK(Name = LOWER(Name))
);

CREATE TABLE IF NOT EXISTS Sensors (
  Id BIGSERIAL PRIMARY KEY,
  RegionID BIGINT REFERENCES Regions(id) ON DELETE CASCADE NOT NULL,
  Name text NOT NULL UNIQUE,
  CHECK(Name = LOWER(Name)),
  Longitude REAL NOT NULL,
  Latitude REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS Readings (
  Id BIGSERIAL PRIMARY KEY,
  SensorId BIGINT REFERENCES Sensors(id) ON DELETE CASCADE NOT NULL,
  Temperature REAL NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT(NOW())
);
